site:
  title: PortFolio
  start_page: PortFolio::index.adoc
content:
  sources:
    - url: .
      branches: [main]
      start_path: docs
    - url: https://github.com/carpepal/MIBudget-back.git
      branches: [main]
      tags: [v*]
      start_path: docs

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-server-url: https://kroki.io
    allow-uri-read: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
